package com.szw.dream.po;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_base
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserBase implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     * Database Column Remarks:
     *   1正常用户 2禁言用户 3虚拟用户 4运营
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.user_role
     *
     * @mbg.generated
     */
    private Byte userRole;

    /**
     * Database Column Remarks:
     *   注册来源：1手机号 2邮箱 3用户名 4qq 5微信 6腾讯微博 7新浪微博
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.register_source
     *
     * @mbg.generated
     */
    private Byte registerSource;

    /**
     * Database Column Remarks:
     *   用户账号，必须唯一
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   用户性别 0-female 1-male
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     * Database Column Remarks:
     *   用户生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.birthday
     *
     * @mbg.generated
     */
    private Long birthday;

    /**
     * Database Column Remarks:
     *   用户个人签名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     * Database Column Remarks:
     *   手机号码(唯一)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   手机号码绑定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile_bind_time
     *
     * @mbg.generated
     */
    private Date mobileBindTime;

    /**
     * Database Column Remarks:
     *   邮箱(唯一)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   邮箱绑定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.email_bind_time
     *
     * @mbg.generated
     */
    private Date emailBindTime;

    /**
     * Database Column Remarks:
     *   头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.face
     *
     * @mbg.generated
     */
    private String face;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   用户设备push_token
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.push_token
     *
     * @mbg.generated
     */
    private String pushToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.uid
     *
     * @return the value of user_base.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.uid
     *
     * @param uid the value for user_base.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.user_role
     *
     * @return the value of user_base.user_role
     *
     * @mbg.generated
     */
    public Byte getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.user_role
     *
     * @param userRole the value for user_base.user_role
     *
     * @mbg.generated
     */
    public void setUserRole(Byte userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.register_source
     *
     * @return the value of user_base.register_source
     *
     * @mbg.generated
     */
    public Byte getRegisterSource() {
        return registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.register_source
     *
     * @param registerSource the value for user_base.register_source
     *
     * @mbg.generated
     */
    public void setRegisterSource(Byte registerSource) {
        this.registerSource = registerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.user_name
     *
     * @return the value of user_base.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.user_name
     *
     * @param userName the value for user_base.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.nick_name
     *
     * @return the value of user_base.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.nick_name
     *
     * @param nickName the value for user_base.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.gender
     *
     * @return the value of user_base.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.gender
     *
     * @param gender the value for user_base.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.birthday
     *
     * @return the value of user_base.birthday
     *
     * @mbg.generated
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.birthday
     *
     * @param birthday the value for user_base.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.signature
     *
     * @return the value of user_base.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.signature
     *
     * @param signature the value for user_base.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile
     *
     * @return the value of user_base.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile
     *
     * @param mobile the value for user_base.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile_bind_time
     *
     * @return the value of user_base.mobile_bind_time
     *
     * @mbg.generated
     */
    public Date getMobileBindTime() {
        return mobileBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile_bind_time
     *
     * @param mobileBindTime the value for user_base.mobile_bind_time
     *
     * @mbg.generated
     */
    public void setMobileBindTime(Date mobileBindTime) {
        this.mobileBindTime = mobileBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.email
     *
     * @return the value of user_base.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.email
     *
     * @param email the value for user_base.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.email_bind_time
     *
     * @return the value of user_base.email_bind_time
     *
     * @mbg.generated
     */
    public Date getEmailBindTime() {
        return emailBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.email_bind_time
     *
     * @param emailBindTime the value for user_base.email_bind_time
     *
     * @mbg.generated
     */
    public void setEmailBindTime(Date emailBindTime) {
        this.emailBindTime = emailBindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.face
     *
     * @return the value of user_base.face
     *
     * @mbg.generated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.face
     *
     * @param face the value for user_base.face
     *
     * @mbg.generated
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.create_time
     *
     * @return the value of user_base.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.create_time
     *
     * @param createTime the value for user_base.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.update_time
     *
     * @return the value of user_base.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.update_time
     *
     * @param updateTime the value for user_base.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.push_token
     *
     * @return the value of user_base.push_token
     *
     * @mbg.generated
     */
    public String getPushToken() {
        return pushToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.push_token
     *
     * @param pushToken the value for user_base.push_token
     *
     * @mbg.generated
     */
    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }
}